"""Add max_attempts to GameSession

Revision ID: 12e5dd1e9204
Revises: ad1a803c7375
Create Date: 2025-12-10 20:32:18.359583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e5dd1e9204'
down_revision = 'ad1a803c7375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_attempts', sa.Integer(), nullable=False))
        batch_op.alter_column('attempts_remaining',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.alter_column('attempts_remaining',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('max_attempts')

    # ### end Alembic commands ###
