"""Initial migration

Revision ID: 170fba97c7dd
Revises: 
Create Date: 2025-11-04 18:16:11.452280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170fba97c7dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('player_name')
    )
    op.create_table('game_session',
    sa.Column('game_session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('secret_code', sa.JSON(), nullable=False),
    sa.Column('attempts_remaining', sa.Integer(), nullable=True),
    sa.Column('is_over', sa.Boolean(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.Column('session_ended', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('game_session_id')
    )
    op.create_table('guess',
    sa.Column('guess_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=False),
    sa.Column('guess_value', sa.JSON(), nullable=False),
    sa.Column('correct_positions', sa.Integer(), nullable=False),
    sa.Column('correct_numbers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.game_session_id'], ),
    sa.PrimaryKeyConstraint('guess_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guess')
    op.drop_table('game_session')
    op.drop_table('player')
    # ### end Alembic commands ###
