"""Add normalized_name to Player

Revision ID: 3f35d795af5f
Revises: 98e07b8c1561
Create Date: 2025-12-09 13:57:45.513504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String


# revision identifiers, used by Alembic.
revision = '3f35d795af5f'
down_revision = '98e07b8c1561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_name', sa.String(length=20), nullable=True))

        # Step 2: Backfill existing records
    player_table = table(
        'player',
        column('player_name', String),
        column('normalized_name', String)
    )

    op.execute(
        player_table.update().values(
            normalized_name=sa.func.lower(player_table.c.player_name)
        )
    )

    # Step 3: Alter the column to NOT NULL and add uniqueness constraint
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('normalized_name', nullable=False)
        batch_op.create_unique_constraint('uq_normalized_name', ['normalized_name'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('uq_normalized_name', type_='unique')
        batch_op.drop_column('normalized_name')

    # ### end Alembic commands ###
