"""Add code_length to GameSession

Revision ID: 9569fe71e03f
Revises: 170fba97c7dd
Create Date: 2025-11-18 21:29:51.731297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9569fe71e03f'
down_revision = '170fba97c7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_length', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_column('code_length')

    # ### end Alembic commands ###
