"""Initial migration with difficulty column

Revision ID: ad1a803c7375
Revises: 
Create Date: 2025-12-10 19:39:17.559601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1a803c7375'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_session',
    sa.Column('game_session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('code_length', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('secret_code', sa.JSON(), nullable=False),
    sa.Column('attempts_remaining', sa.Integer(), nullable=True),
    sa.Column('is_over', sa.Boolean(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.Column('session_ended', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('game_session_id')
    )
    with op.batch_alter_table('guess', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'game_session', ['game_session_id'], ['game_session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guess', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('game_session')
    # ### end Alembic commands ###
