"""Removed default 4 from code_length in GameSession model

Revision ID: af936f5ec5e2
Revises: 3f35d795af5f
Create Date: 2025-12-09 18:19:55.353985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af936f5ec5e2'
down_revision = '3f35d795af5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.alter_column('code_length',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.alter_column('code_length',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
